from renight_core import VERSION

HELP_HTML = (
    f"<h2>ReNightdive Local Wad Manager (v{VERSION})</h2>"
    "<p>ReNight is a small utility for managing local DOOM WADs for the Nightdive "
    "'DOOM + DOOM II' KEX 2024 source port. It copies or symlinks WAD files into the "
    "game's Nightdive mod folder so they appear in the in-game <b>Local Mods</b> list.</p>"
    "<h3>Folders</h3>"
    "<ul>"
    "<li><b>Nightdive Folder:</b> The folder where the KEX port loads local mods from. "
    "On first run the program tries to auto-detect it (including common Steam/Proton layouts). "
    "If detection is wrong or you use a non-standard setup, set it manually.</li>"
    "<li><b>PWADs Folder:</b> A root folder where you keep your WADs and subfolders. "
    "It is only used for browsing and for matching existing files; you can still import "
    "from anywhere on disk.</li>"
    "</ul>"
    "<h3>Import Modes</h3>"
    "<ul>"
    "<li><b>Create as .symlink:</b> When enabled, ReNight creates symbolic links in the "
    "Nightdive Folder that point to the original WADs in your PWAD tree. This saves disk "
    "space and keeps a single copy of each file, but requires symlink support on your OS.</li>"
    "<li>When symlinks are <b>not</b> used, ReNight copies the WADs into the Nightdive "
    "Folder. The original files in your PWAD tree are never modified.</li>"
    "<li>If you import a WAD whose filename already exists in the Nightdive Folder and the "
    "contents differ, ReNight creates a new file with an appended number "
    "(for example, <code>d-zjointed-2.wad</code>, <code>d-zjointed-3.wad</code>, and so on).</li>"
    "</ul>"
    "<h3>Basic Workflow</h3>"
    "<ul>"
    "<li>Set the <b>Nightdive Folder</b> and optional <b>PWADs Folder</b>.</li>"
    "<li>Use <b>Pick WAD</b> to select one or more WAD files, or <b>Pick Folder (Batch)</b> "
    "to import every <code>.wad</code> in a directory.</li>"
    "<li>The <b>Import</b> button lights up with the current selection. Click it to create "
    "symlinks or copies according to your settings.</li>"
    "<li>All mods currently present in the Nightdive Folder are listed in the right-hand pane.</li>"
    "</ul>"
    "<h3>Mod Status Tags</h3>"
    "<p>The mod list shows each entry as a filename plus a status tag in the right column:</p>"
    "<ul>"
    "<li><b>(SL):</b> The entry in the Nightdive Folder is a symbolic link.</li>"
    "<li><b>(CPY):</b> A copied WAD that ReNight can tie back to a real file in your "
    "PWAD tree. Matching is done using the stored metadata when possible, and otherwise by "
    "filename + MD5 against your PWADs Folder (including subfolders).</li>"
    "<li><b>(ONL):</b> A WAD that currently exists only in the Nightdive Folder. This usually "
    "means it was added manually, imported from outside the PWAD tree, or its original source "
    "file has since been moved or deleted.</li>"
    "</ul>"
    "<p>Classification is recomputed every time the list is refreshed. If a source file "
    "disappears, a former (CPY) entry will fall back to (ONL). If a matching WAD appears "
    "under your PWAD tree later, it will be upgraded back to (CPY).</p>"
    "<h3>Live Updates</h3>"
    "<p>ReNight monitors your Nightdive Folder and the selected PWADs Folder for filesystem "
    "changes and refreshes the mod list automatically when WAD files are added, removed, or replaced.</p>"
    "<h3>Deleting Mods</h3>"
    "<ul>"
    "<li>Select one or more rows in the mod list and click <b>Delete Selected Mod(s)</b> to "
    "remove the corresponding files or symlinks from the Nightdive Folder.</li>"
    "<li>Deleting an <b>(ONL)</b> entry shows a warning, since that file has no known copy "
    "in your PWAD tree.</li>"
    "<li>Deletion only affects the Nightdive Folder. Your PWADs Folder is never touched.</li>"
    "</ul>"
    "<h3>Limitations</h3>"
    "<ul>"
    "<li>The KEX port only loads single-WAD mods via the in-game UI. Multi-WAD setups still "
    "require custom launch parameters.</li>"
    "<li><code>.pk3</code>, UDMF maps, or generic \"ZDoom mods\" are not supported by the "
    "Nightdive KEX port, and ReNight cannot change that.</li>"
    "<li>\"Compressed WADs\" (for example, WADs stored inside <code>.zip</code> or other "
    "unusual WAD formats) are not supported by the Nightdive KEX port; it expects plain "
    "<code>.wad</code> files.</li>"
    "</ul>"
    "<h3>Help, Updates, and Bug Reports</h3>"
    "<ul>"
    "<li>The bottom bar of this Help window provides a <b>Check for updates</b> "
    "button that runs ReNight's built-in update checker, and a <b>Report a bug</b> button that "
    "opens the GitHub issue tracker.</li>"
    "<li>You can always find the latest releases and documentation at the project page:</li>"
    "</ul>"
    "<p><a href='https://github.com/Retzilience/ReNight'>https://github.com/Retzilience/ReNight</a></p>"
    "<h3>Credits</h3>"
    "<ul>"
    "<li>Made with love, rip and tear by "
    "<span style='font-weight: bold; font-size: 1.1em; letter-spacing: 0.5px;'>retzilience</span>.</li>"
    "<li>Logo by "
    "<span style='font-weight: bold; font-size: 1.1em; letter-spacing: 0.5px;'>RataUnderground</span>.</li>"
    "<li>License: CC BY-NC-SA 4.0, 2024.</li>"
    "</ul>"
)
